[package]
name = "exampe-01"
version = "0.1.0"
authors = ["ppcamp <p.augustocampos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.3"
ntex = "0.3.2"
